# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POa-svx_oASaI1aQL23hcZU7rBDbgbwZ
"""

import random

def guess_the_number():
    # Generate a random number between 1 and 100
    number_to_guess = random.randint(1, 100)
    attempts = 0
    guessed = False

    print("Welcome to 'Guess the Number' game!")
    print("I have generated a random number between 1 and 100.")

    while not guessed:
        # Prompt the user to input their guess
        user_guess = input("Please enter your guess: ")

        try:
            user_guess = int(user_guess)
            attempts += 1

            # Compare the guess to the generated number
            if user_guess < number_to_guess:
                print("Too low! Try again.")
            elif user_guess > number_to_guess:
                print("Too high! Try again.")
            else:
                guessed = True
                print(f"Congratulations! You've guessed the number {number_to_guess} in {attempts} attempts.")
        except ValueError:
            print("Invalid input. Please enter a valid number.")

if __name__ == "__main__":
    guess_the_number()